version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - inception-network
networks:
  inception-network:
    name: inception
    driver: bridge
