version: '3'
services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wordpress-data:/var/www/html/
  
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception-network
    volumes:
      - db-data:/var/lib/mysql/
  
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    networks:
      - inception-network
    volumes:
      - wordpress-data:/var/www/html/

  php-admin:
    depends_on:
      - mariadb
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - inception-network
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      #- PMA_USER=root
      #- PMA_PASSWORD=user123
      #- PMA_ROOT_PASSWORD=root123

volumes:
  db-data:
    name: db-data
    driver: local
  wordpress-data:
    name: wordpress-data
    driver: local
  
networks:
  inception-network:
    name: inception
    driver: bridge
