version: '3.8'
services:
  nginx:
    build: ./nginx
    depends_on:
      - wordpress
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception-network
    volumes:
      - wp-data:/var/www/html/
  
  mariadb:
    build: ./mariadb
    container_name: mariadb
    networks:
      - inception-network
    volumes:
      - db-data:/var/lib/mysql/
    env_file:
      - .env
  
  wordpress:
    build: ./wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    networks:
      - inception-network
    volumes:
      - wp-data:/var/www/html/
    env_file:
      - .env

volumes:
  db-data:
    name: db-data
    driver_opts:
      type: none
      device: /home/dsilveri/data/mysql
      o: bind
      
  wp-data:
    name: wp-data
    driver_opts:
      type: none
      device: /home/dsilveri/data/wordpress
      o: bind

networks:
  inception-network:
    name: inception
    driver: bridge
